// USER ACTIONS
export const AUTH_USER_PENDING = 'AUTH_USER_PENDING';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';
export const UPDATE_ME = 'UPDATE_ME';

export const USER_LOGOUT_PENDING = 'USER_LOGOUT_PENDING';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR';

export const CHECK_USER_LOGGED_IN_PENDING = 'CHECK_USER_LOGGED_IN_PENDING';
export const CHECK_USER_LOGGED_IN_SUCCESS = 'CHECK_USER_LOGGED_IN_SUCCESS';
export const CHECK_USER_LOGGED_IN_ERROR = 'CHECK_USER_LOGGED_IN_ERROR';

// MISC
export const AJAX_ERROR = 'AJAX_ERROR';
export const RESET_STATE = 'RESET_STATE';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const IMAGE_INFORMATION = 'IMAGE_INFORMATION';